project_id = "ucylyiemqzhsbjbkewxt"

[functions.vauner-sync]
verify_jwt = false

[functions.process-products]
verify_jwt = false

[functions.extract-product-info]
verify_jwt = false

[functions.import-vehicle-models]
verify_jwt = false

[functions.match-vehicle-years]
verify_jwt = false

[functions.resume-processing]
verify_jwt = false

[functions.process-product-image]
verify_jwt = false

[functions.import-vehicle-compatibility]
verify_jwt = false